"""Try to manually write messages

Revision ID: a34c098b28ca
Revises: 
Create Date: 2023-11-24 14:47:08.268469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34c098b28ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    
      
    op.create_table(
        'roles',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), unique=True, nullable=False),
    )

        
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(50), unique=True, nullable=False),
        sa.Column('password', sa.String(100), nullable=False),
        sa.Column('role_id', sa.Integer, sa.ForeignKey('roles.id'), nullable=False),
    )


    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String(100), nullable=False),
        sa.Column('status', sa.String(20), nullable=False, default='Pending'),
        sa.Column('assigned_to', sa.Integer, sa.ForeignKey('users.id')),
        sa.Column('assigned_by', sa.Integer, sa.ForeignKey('users.id')),
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    op.drop_table('roles')

    op.drop_index('name', table_name='users')
    op.drop_table('users')

    op.drop_index('name', table_name='tasks')
    op.drop_table('tasks')
  

    # ### end Alembic commands ###
